
[project]
name = "pico-ota-backend"
version = "0.1.0"
description = "Minimal FastAPI backend for Pico OTA manager"
requires-python = ">=3.11"
dependencies = [
  "fastapi>=0.111.0",
  "uvicorn[standard]>=0.30.0",
  "pydantic-settings>=2.3.0",
]

[project.optional-dependencies]
dev = ["pytest", "httpx", "ruff", "black"]

[tool.ruff]
line-length = 100
